name: blackduck-explicit-plugin
kind: workflow
apiVersion: automation.cloudbees.io/v1alpha1

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'


permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

          
jobs:
  blackduck-scan:
    steps:

      - name: Scan with Black Duck SCA with params
        uses: cloudbees-io/blackduck-sca-scan-dependency@v2
        with:
          server-url: ${{ vars.BLACK_DUCK_URL }}
          api-token: ${{ secrets.BLACK_DUCK_TOKEN }}
          ref: main
    